<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-KDDF7SM0" name="com.way2automation.qa.testcases.LinkPageTest" tests="9" failures="1" timestamp="3 Jun 2022 13:22:51 GMT" time="123.400" errors="0">
  <testcase name="ClickOnHome19v3LinkTest" time="13.006" classname="com.way2automation.qa.testcases.LinkPageTest"/>
  <testcase name="ClickOnHomeLinkTest" time="12.987" classname="com.way2automation.qa.testcases.LinkPageTest"/>
  <testcase name="ClickOnMovedLinkTest" time="11.851" classname="com.way2automation.qa.testcases.LinkPageTest"/>
  <testcase name="ClickOnUnauthorizedLinkTest" time="13.753" classname="com.way2automation.qa.testcases.LinkPageTest"/>
  <testcase name="ClickOnBadRequestLinkTest" time="12.938" classname="com.way2automation.qa.testcases.LinkPageTest"/>
  <testcase name="ClicOnNotFoundLinkTest" time="20.183" classname="com.way2automation.qa.testcases.LinkPageTest">
    <failure type="java.lang.AssertionError" message="expected [Link has responded with staus 405 and status text Not Found] but found [Link has responded with staus 404 and status text Not Found]">
      <![CDATA[java.lang.AssertionError: expected [Link has responded with staus 405 and status text Not Found] but found [Link has responded with staus 404 and status text Not Found]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.way2automation.qa.pages.LinksPage.ClickOnNotFoundLink(LinksPage.java:159)
	at com.way2automation.qa.testcases.LinkPageTest.ClicOnNotFoundLinkTest(LinkPageTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- ClicOnNotFoundLinkTest -->
  <testcase name="ClickOnCreatedLinkTest" time="13.349" classname="com.way2automation.qa.testcases.LinkPageTest"/>
  <testcase name="ClickOnNoContentLinkTest" time="12.164" classname="com.way2automation.qa.testcases.LinkPageTest"/>
  <testcase name="ClickOnForbiddenLinkTest" time="13.169" classname="com.way2automation.qa.testcases.LinkPageTest"/>
</testsuite> <!-- com.way2automation.qa.testcases.LinkPageTest -->
